### ISSUE TITLE
Default user login

### ISSUE THREAD

**Issue by hendisantika** [gustavoponce7/SpringBootPrimeFacesIntegration#1]
Nice repo.

But, I want to know what is user login (username and password) to login?

Thanks

**Comment by gustavoponce7** [comment]
Hi buddy, sorry for the late reply but I was relocating to a new country and I was some kind of busy :S

Here the information:

1. When you will launch the application for the first time, go to application.properties file and set **spring.datasource.initialize=true** (return the value to false when the application will be relaunched)
2. Go to http://localhost:8080/registration.faces and register your user
3. Go to http://localhost:8080/login.faces and login with your credentials

I hope it can help

Regards
Gustavo
